### ISSUE TITLE
running inside docker fails

### ISSUE THREAD

**Issue by lgfausak** [akfullfo/taskforce#15]
Hey Andy :-)

I am seeing an error inside docker.  I was thinking this would be a great utility for docker, because it needs to have things started, usually with different roles.

```
[install@fb7ca5870ac0 taskforce]$ bin/taskforce -f /tmp/t.conf
Traceback (most recent call last):
  File "bin/taskforce", line 190, in <module>
    log_handler = logging.handlers.SysLogHandler(**logparams)
  File "/usr/lib64/python2.7/logging/handlers.py", line 760, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib64/python2.7/logging/handlers.py", line 788, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied

```

**Comment by akfullfo** [comment]
We run taskforce in containers all the time. Working from memory (still traveling), I think it will try to create a Unix domain control socket by default, probably in /var/run. You could either disable it in the config, point it some where else, or run taskforce as root.

a.

**Comment by lgfausak** [comment]
thanks.  got it working with a -e switch. you know, this is a great replacement for systemctl or inittab!

**Comment by lgfausak** [comment]
no longer an issue with -e switch.
